### DISCUSSION TITLE
Add a Test Suite (Continuous Integration)

### DISCUSSION THREAD

**Discussion by gggeek** [timschofield/webERP#444] [Development Discussion & Specification]
It might be as simple as starting out with a github action which:
- sets up the system with  a known db and config file
- send a bunch of http requests to known URLs and checks that they respond with a 200OK and with some specific html tag in the page

**Comment by dalers** [comment]
Thanks @gggeek. sharing your insights. I can use git and GitHub, but this is at such a higher level!

I asked Gemini for more detail, but I don't understand where the web server is. Do I need to provide the web/PHP server?

--------------------

Setting up a GitHub Action to import an SQL file into MariaDB and then send HTTP requests to known URLs, confirming a 200 OK status and the presence of a specific HTML tag, involves several steps. Below is a comprehensive guide.

## GitHub Action Workflow: SQL Import and HTTP Check

This workflow will consist of a few jobs, or a single job with multiple steps, depending on your preference for sequential execution and isolation. We'll use a single job for simplicity, executing steps sequentially.

### Prerequisites:

  * **GitHub Repository:** Your code and the SQL file (`your_database.sql`) should be in a GitHub repository.
  * **MariaDB Instance:** You'll need a MariaDB instance accessible from GitHub Actions. This could be a Docker container spun up within the workflow, a remote server, or a cloud-managed database. For this example, we'll assume a Docker container within the workflow.
  * **Database Credentials:** Securely store your database credentials as GitHub Secrets.
      * `DB_HOST` (e.g., `127.0.0.1` if using a service container)
      * `DB_PORT` (e.g., `3306`)
      * `DB_USER`
      * `DB_PASSWORD`
      * `DB_NAME`
  * **Target URLs:** The URLs you want to check.
  * **Specific HTML Tag:** The HTML tag (and optionally its content) you're looking for.

### Workflow File (`.github/workflows/your_workflow_name.yml`):

Create a new file in your repository at `.github/workflows/your_workflow_name.yml` and add the following content:

```yaml
name: Database Import and Health Check

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    # Define MariaDB service container
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }} # Or a dedicated user
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306 # Map container port to host for access if needed, though within workflow, service name is enough
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }}" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MariaDB client (optional, but good for direct interaction)
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client

      - name: Wait for MariaDB to be ready
        run: |
          # This waits for the MariaDB service to be healthy within the workflow
          # The `services` block's healthcheck should handle most of this,
          # but an explicit wait can be useful for more complex scenarios.
          for i in $(seq 1 30); do
            mysql -h 127.0.0.1 -P 3306 -u root -p"${{ secrets.DB_PASSWORD }}" -e "SELECT 1" > /dev/null 2>&1 && echo "MariaDB ready." && break
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Import SQL file into MariaDB
        run: |
          mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" ${{ secrets.DB_NAME }} < your_database.sql
        env:
          DB_HOST: 127.0.0.1 # Or the service name if using it directly
          DB_PORT: 3306
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Send HTTP Requests and Validate Responses
        run: |
          URLS=(
            "https://www.example.com"
            "https://your-application-url.com/some-page"
            # Add more URLs as needed
          )
          EXPECTED_TAG="<h1" # Or "<div id=\"my-element\"" or "Welcome to our site"

          for URL in "${URLS[@]}"; do
            echo "Checking URL: $URL"
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            
            if [ "$RESPONSE" != "200" ]; then
              echo "Error: $URL responded with HTTP status $RESPONSE instead of 200 OK."
              exit 1
            fi

            echo "HTTP 200 OK for $URL. Checking for specific HTML tag..."
            
            # Fetch the page content to check for the tag
            PAGE_CONTENT=$(curl -s "$URL")

            if ! echo "$PAGE_CONTENT" | grep -q "$EXPECTED_TAG"; then
              echo "Error: Specific tag '$EXPECTED_TAG' not found in $URL."
              exit 1
            fi

            echo "Specific tag '$EXPECTED_TAG' found in $URL."
            echo "---"
          done

      - name: Cleanup (Optional: If MariaDB was a service, it's cleaned automatically)
        run: |
          echo "Workflow completed successfully."
```

### Explanation of Each Section:

#### 1\. Workflow Configuration:

  * **`name: Database Import and Health Check`**: A descriptive name for your workflow.
  * **`on: push: branches: - main`**: This defines when the workflow will run. In this case, it triggers on every push to the `main` branch.
  * **`workflow_dispatch:`**: This allows you to manually trigger the workflow from the GitHub Actions tab in your repository, which is useful for testing.

#### 2\. Jobs:

  * **`jobs: build:`**: Defines a single job named `build`. You can have multiple jobs if you want to parallelize or separate concerns.
  * **`runs-on: ubuntu-latest`**: Specifies the operating system the job will run on. `ubuntu-latest` is a good default.

#### 3\. MariaDB Service Container:

  * **`services: mariadb:`**: This is a powerful feature of GitHub Actions that allows you to run a Docker container as a service alongside your job.
      * **`image: mariadb:latest`**: Uses the latest official MariaDB Docker image.
      * **`env:`**: Sets environment variables for the MariaDB container.
          * `MYSQL_ROOT_PASSWORD`: Essential for the MariaDB container. It's best to use a GitHub Secret here (`${{ secrets.DB_PASSWORD }}`).
          * `MYSQL_DATABASE`: Specifies the database to create on startup.
      * **`ports: - 3306:3306`**: Maps port 3306 inside the container to port 3306 on the host. While within the workflow, you can refer to the service by its name (`mariadb`), explicit port mapping can be helpful for debugging or if you need to access it from another service directly.
      * **`options: --health-cmd="..."`**: This defines a health check for the MariaDB service. The workflow will wait for this health check to pass before proceeding to subsequent steps. This is crucial for ensuring the database is ready before you try to import data.

#### 4\. Steps:

  * **`name: Checkout repository`**:

      * `uses: actions/checkout@v4`: This standard action checks out your repository's code into the runner, making your `your_database.sql` file available.

  * **`name: Install MariaDB client`**:

      * `run: sudo apt-get update && sudo apt-get install -y mariadb-client`: Installs the MariaDB client utilities (`mysql`) on the runner. This is necessary to interact with the MariaDB server.

  * **`name: Wait for MariaDB to be ready`**:

      * `run: | ...`: Although the `services` block has a `health-cmd`, sometimes a more explicit wait loop using the `mysql` client is beneficial, especially if the `health-cmd` isn't robust enough for your specific setup. This loop repeatedly tries to connect to the MariaDB instance until it succeeds or times out.

  * **`name: Import SQL file into MariaDB`**:

      * `run: mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" ${{ secrets.DB_NAME }} < your_database.sql`: This is the core command for importing your SQL file.
          * `-h 127.0.0.1`: The host where MariaDB is running. Since it's a service container, `127.0.0.1` works as the runner can access its own Docker bridge network. Alternatively, you can use the service name `mariadb`.
          * `-P 3306`: The port MariaDB is listening on.
          * `-u ${{ secrets.DB_USER }}`: The database username, retrieved from GitHub Secrets.
          * `-p"${{ secrets.DB_PASSWORD }}"`: The database password, retrieved from GitHub Secrets. **Crucially, double-quote the password to handle special characters.**
          * `${{ secrets.DB_NAME }}`: The database name.
          * `< your_database.sql`: Redirects the content of `your_database.sql` as input to the `mysql` command.
      * `env:`: Although the `run` command directly uses secrets, defining them in the `env` block can make the script cleaner and more reusable if you had multiple commands needing these.

  * **`name: Send HTTP Requests and Validate Responses`**:

      * `run: | ...`: This step uses `curl` and `grep` to perform the HTTP checks.
      * `URLS=( ... )`: An array of URLs to test. Modify this with your actual application URLs.
      * `EXPECTED_TAG="<h1"`: The specific HTML string you expect to find. This could be an opening tag (`<title>`), an element with an ID (`<div id="main-content">`), or even a specific piece of text like "Welcome to our application".
      * **Loop through URLs:**
          * `RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")`: This command sends a `curl` request:
              * `-s`: Silent mode (don't show progress or error messages).
              * `-o /dev/null`: Discard the actual response body.
              * `-w "%{http_code}"`: Only output the HTTP status code.
          * **HTTP Status Check:** `if [ "$RESPONSE" != "200" ]; then ... exit 1; fi`: Checks if the HTTP status code is exactly "200". If not, it prints an error and exits the workflow with a failure.
          * **HTML Tag Check:**
              * `PAGE_CONTENT=$(curl -s "$URL")`: Fetches the *entire* page content this time.
              * `if ! echo "$PAGE_CONTENT" | grep -q "$EXPECTED_TAG"; then ... exit 1; fi`: Pipes the page content to `grep`:
                  * `-q`: Quiet mode (don't print matching lines).
                  * `"$EXPECTED_TAG"`: The pattern to search for.
              * If `grep` doesn't find the pattern (indicated by `!`), it prints an error and fails the workflow.

#### 5\. Cleanup (Optional):

  * The MariaDB service container will be automatically shut down and cleaned up by GitHub Actions when the job completes. The explicit "Cleanup" step is more for illustrative purposes or if you had external resources to clean up.

### How to Set Up GitHub Secrets:

1.  In your GitHub repository, go to **Settings**.
2.  In the left sidebar, click **Secrets and variables** \> **Actions**.
3.  Click **New repository secret**.
4.  Add the following secrets, one by one:
      * `DB_HOST` (e.g., `127.0.0.1` or `mariadb`)
      * `DB_PORT` (e.g., `3306`)
      * `DB_USER` (e.g., `root` or your specific DB user)
      * `DB_PASSWORD` (Your MariaDB password)
      * `DB_NAME` (The name of the database you're importing into)

### Placing Your SQL File:

Ensure your SQL file (e.g., `your_database.sql`) is located at the root of your repository or in a clearly defined path that you specify in the `Import SQL file into MariaDB` step.

### Running the Workflow:

1.  Push the `your_workflow_name.yml` file to your `main` branch.
2.  Go to the "Actions" tab in your GitHub repository.
3.  You should see your "Database Import and Health Check" workflow running. You can also trigger it manually if you included `workflow_dispatch`.

### Troubleshooting Tips:

  * **Secrets:** Double-check that your GitHub Secrets are correctly set and the names match exactly in your workflow file.
  * **Database Connectivity:** If the SQL import fails, check the MariaDB service logs in the GitHub Actions run for connection errors or authentication issues. Ensure the `DB_HOST` and `DB_PORT` are correct.
  * **SQL File Path:** Verify that `your_database.sql` is in the expected location.
  * **Permissions:** Ensure the database user has the necessary permissions to create tables and insert data.
  * **Curl and Grep:** If the HTTP checks fail, inspect the `curl` and `grep` commands carefully. Print the `RESPONSE` and `PAGE_CONTENT` variables to debug what they contain.
  * **Expected Tag:** Make sure `EXPECTED_TAG` is specific enough to avoid false positives but not so specific that minor page changes break the test. Consider using unique IDs or classes if available.
  * **MariaDB Health Check:** Pay attention to the health check logs for the MariaDB service. If it's not becoming healthy, the subsequent steps will fail. You might need to adjust the `health-cmd` or `health-interval`.

This setup provides a robust way to automate your database seeding and application health checks within your CI/CD pipeline.
